Algoritmo "semnome"
//Faça um algoritmo para ler os números das matrículas e quatro notas de vários alunos.

Var
matricula, alunos: inteiro
n1, n2, n3, n4: real


Inicio

escreva ("Quantos alunos tem sua turma? ")
leia (alunos)

escreval

para alunos de 1 ate alunos passo 1 faca
     escreva ("Digite o número de matricula: ")
     leia (matricula)

     escreval

     escreval ("Digite as quatro notas do aluno: ")
     leia (n1, n2, n3, n4)
     
     escreval

fimpara

Fimalgoritmo