Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2020
Var
// Seção de Declarações das variáveis 
n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

n <- 9

enquanto (n >= 9) e (n <= 15) faca
         escreval ("Contador:", n)
         n <- n+1
fimenquanto

Fimalgoritmo