algoritmo "Emprego"
// Disciplina: [Linguagem e Lógica de Programação}
// Professor(a): BeCode

var

n1, n2, soma: Inteiro
                 
inicio

escreva ("Digite o primeiro número da multiplicação: ")
leia (n1)

escreva ("Digite o segundo número da multiplicação: ")
leia (n2)

soma <- 0

repita
      soma <- soma + n1
ate soma = (n1*n2))

fimrepita

escreval (n1, " *", n2, " =", soma)

fimalgoritmo
